name = "feature-trail"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "KV_STORE"
id = "<your kv id>"

[vars]
VITE_SITE_TITLE = "Feature Trail"
VITE_SUPPORT_EMAIL = "support@example.com"
VITE_SUPPORT_OTHER_NAME = "Discord"
VITE_SUPPORT_OTHER_URL = "https://discord.gg/your-discord-invitation"
SPREADSHEET_ID = "<your spreadsheet id>"
SPREADSHEET_FEATURES_RANGE = "Sheet1"
SPREADSHEET_FEATURES_MAPPING = '{"uuid":"ID","title":"Title","description":"Description","timestamp":"Timestamp","isComplete":"IsComplete","needsFeedback":"NeedsFeedback","inProgress":"InProgress","targetRelease":"TargetRelease"}'
